BookStore/BookStore/Controllers/CartController.cs
using BookStore.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStore.Models;
namespace BookStore.Controllers
{
    public class CartController : Controller
    {
        bookstoreEntities obj = new bookstoreEntities();
        // GET: Cart
        public ActionResult Index()
        {
            return View((List<CartModel>)Session["cart"]);
        }
        [HttpPost]
        public ActionResult AddToCart(string id, int quantity)
        {
            if (Session["cart"] == null)
            {
                List<CartModel> cart = new List<CartModel>();
                cart.Add(new CartModel { Sach = obj.Sach.Find(id), soLuong = quantity });
                Session["cart"] = cart;
                Session["count"] = 1;
            }
            else
            {
                List<CartModel> cart = (List<CartModel>)Session["cart"];
                //kiểm tra sản phẩm có tồn tại trong giỏ hàng chưa???
                int index = isExist(id);
                if (index != -1)
                {
                    //nếu sp tồn tại trong giỏ hàng thì cộng thêm số lượng
                    cart[index].soLuong += quantity;
                }
                else
                {
                    //nếu không tồn tại thì thêm sản phẩm vào giỏ hàng
                    cart.Add(new CartModel { Sach = obj.Sach.Find(id), soLuong = quantity });
                    //Tính lại số sản phẩm trong giỏ hàng
                    Session["count"] = Convert.ToInt32(Session["count"]) + 1;
                }
                Session["cart"] = cart;
            }
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }

        private int isExist(string id)
        {
            List<CartModel> cart = (List<CartModel>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].Sach.maSach.Equals(id))
                    return i;
            return -1;
        }

        //xóa sản phẩm khỏi giỏ hàng theo id
        public ActionResult Remove(string Id)
        {
            List<CartModel> li = (List<CartModel>)Session["cart"];
            li.RemoveAll(x => x.Sach.maSach == Id);
            Session["cart"] = li;
            Session["count"] = Convert.ToInt32(Session["count"]) - 1;
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }
    }
}

BookStore/BookStore/Controllers/CategoryController.cs
using BookStore.Context;
using BookStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.Controllers
{
    public class CategoryController : Controller
    {
        bookstoreEntities objModel = new bookstoreEntities();
        // GET: Category
        public ActionResult Index()
        {
            HomeModel model = new HomeModel();
            model.ListTheLoaiGoc = objModel.TheLoaiGoc.ToList();
            model.ListTheLoai = objModel.TheLoaiCon.ToList();
            return View(model);
        }
        public ActionResult ProductCategory(String id)
        {
            HomeModel model = new HomeModel();
            model.ListProduct = objModel.Sach.Where(n => n.maTheLoai == id).ToList();
            model.ListTheLoai = objModel.TheLoaiCon.Where(n => n.maTheLoaiGoc == id).ToList();
            if (model.ListProduct.Count==0)
            {
                model.ListProduct = new List<Sach>();
            foreach (var item in model.ListTheLoai)
            {
                model.ListProduct.AddRange(objModel.Sach.Where(n => n.maTheLoai == item.maTheLoaiCon).ToList());
            }

            }
                return View(model);
            
        }
        public ActionResult Listing()
        {
            HomeModel model = new HomeModel();
            model.ListProduct = objModel.Sach.ToList();
            return View(model);
        }

    }
}

BookStore/BookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>


    <meta charset="utf-8">
    <meta http-equiv="pragma" content="no-cache" />
    <meta http-equiv="cache-control" content="max-age=604800" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Nhà Sách Trực Tuyến FAHASA</title>

    <link rel="icon" href="https://cdn0.fahasa.com/media/favicon/default/favicon4.ico" type="image/x-icon" />
    <link rel="shortcut icon" href="https://cdn0.fahasa.com/media/favicon/default/favicon4.ico" type="image/x-icon" />


    <!-- jQuery -->
    <script src="~/Content/js/jquery-2.0.0.min.js" type="text/javascript"></script>

    <!-- Bootstrap4 files-->
    <script src="~/Content/js/bootstrap.bundle.min.js" type="text/javascript"></script>
    <link href="~/Content/css/bootstrap.css" rel="stylesheet" type="text/css" />

    <!-- Font awesome 5 -->
    <link href="~/Content/fonts/fontawesome/css/all.min.css" type="text/css" rel="stylesheet">

    <!-- custom style -->
    <link href="~/Content/css/ui.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/css/responsive.css" rel="stylesheet" type="text/css" />

    <!-- custom javascript -->
    <script src="~/Content/js/script.js" type="text/javascript"></script>

</head>

<body>
    <header class="section-header">
        <section class="header-main border-bottom">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-xl-2 col-lg-3 col-md-12">
                        <a href="http://bootstrap-ecommerce.com" class="brand-wrap">
                            <img class="logo" src="~/Content/images/logo-fhs.png">
                        </a> <!-- brand-wrap.// -->
                    </div>
                    <div class="col-xl-6 col-lg-5 col-md-6">
                        <form action="#" class="search-header">
                            <div class="input-group w-100">
                                <select class="custom-select border-right" name="category_name">
                                    <option value="">All type</option>
                                    <option value="codex">Special</option>
                                    <option value="comments">Only best</option>
                                    <option value="content">Latest</option>
                                </select>
                                <input type="text" class="form-control" placeholder="Search">

                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit">
                                        <i class="fa fa-search"></i> Search
                                    </button>
                                </div>
                            </div>
                        </form> <!-- search-wrap .end// -->
                    </div> <!-- col.// -->
                    <div class="col-xl-4 col-lg-4 col-md-6">
                        <div class="widgets-wrap float-md-right">
                            <div class="widget-header mr-3">
                                @if (Session["idUser"] != null)
                                {
                                    @Html.ActionLink("Logout", "logout", "Home", new { @class = "widget-view" })
                                }
                                else
                                {
                                    @Html.ActionLink("Đăng Nhập", "login", "Home", new { @class = "widget-view" })
                                    @Html.ActionLink("Đăng Kí", "Register", "Home", new { @class = "widget-view" })
                                }
                            </div>
                            <div class="widget-header">
                                <a href="@Url.Action("Index","Cart")" class="widget-view">
                                    <div class="icon-area">
                                        <i class="fa fa-shopping-cart"></i>
                                        <span class="notify" id="CartCount">@Session["count"]</span>
                                    </div>
                                    <small class="text"> Giỏ Hàng </small>
                                </a>
                            </div>
                        </div> <!-- widgets-wrap.// -->
                    </div>



                </div> <!-- row.// -->
            </div> <!-- container.// -->
        </section> <!-- header-main .// -->


        <nav class="navbar navbar-main navbar-expand-lg border-bottom">
            <div class="container">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main_nav" aria-controls="main_nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="main_nav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <span class="nav-link">
                                <i class="fa fa-bars text-muted mr-2"></i>
                                Danh Mục
                            </span>

                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Trang Chủ", "Index", "Home", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Chủ Đề", "Index", "Category", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Sản Phẩm", "Listing", "Category", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Giới Thiệu", "gioiThieu", "Home", null, new { @class = "nav-link" })
                        </li>
                    </ul>
                </div> <!-- collapse .// -->
            </div> <!-- container .// -->
        </nav>
    </header> <!-- section-header.// -->

    @RenderBody()
   
    <!-- ========================= FOOTER ========================= -->
    <footer class="section-footer bg-secondary">
        <div class="container">
            <section class="footer-top padding-y-lg text-white">
                <div class="row">
                    <aside class="col-md col-6">
                        <h6 class="title">Nhà Xuất Bản</h6>
                        <ul class="list-unstyled">
                            <li> <a href="#">Kim Đồng</a></li>
                            <li> <a href="#">Trí Book</a></li>
                            <li> <a href="#">Dân Trí</a></li>
                            <li> <a href="#">Thanh Niên</a></li>
                        </ul>
                    </aside>
                    <aside class="col-md">
                        <h6 class="title">Mạng Xã Hội</h6>
                        <ul class="list-unstyled">
                            <li><a href="https://www.facebook.com/fahasa/"> <i class="fab fa-facebook"></i> Facebook </a></li>
                            <li><a href="https://twitter.com/i/flow/login?redirect_after_login=%2FFahasa_com"> <i class="fab fa-twitter"></i> Twitter </a></li>
                            <li><a href="https://www.instagram.com/fahasa_official"> <i class="fab fa-instagram"></i> Instagram </a></li>
                            <li><a href="https://www.youtube.com/FahasacomChannel"> <i class="fab fa-youtube"></i> Youtube </a></li>
                        </ul>
                    </aside>
                    <aside class="col-md">
                        <h6 class="title">Liên Hệ</h6>
                        <ul class="list-unstyled">
                            <li> <i class="fa fa-map"></i> 60-20 Lê Lợi, Quận 1, TP. HCM </li>
                            <li><i class="fa fa-envelope"></i> cskh@fahasa.com.vn </li>
                            <li> <i class="fa fa-phone"></i> 1900636467 </li>                          
                        </ul>
                    </aside>
                    <aside class="col-md">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15677.95187280105!2d106.6810745871582!3d10.773889!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752f47b7f98daf%3A0xccd180ed07640178!2zTmjDoCBzw6FjaCBTw6BpIEfDsm4!5e0!3m2!1svi!2s!4v1703093341288!5m2!1svi!2s" width="400" height="200" style="border:1;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                    </aside>
                </div> <!-- row.// -->
            </section>	<!-- footer-top.// -->

            <section class="footer-bottom text-center">

                <p class="text-white">Giấy chứng nhận Đăng ký Kinh doanh số 0304132047 do Sở Kế hoạch và Đầu tư Thành phố Hồ Chí Minh cấp ngày 20/12/2005, đăng ký thay đổi lần thứ 10, ngày 20/05/2022</p>
                <p class="text-muted">Bản quyền © 2023 Công ty CP phát hành sách TP HCM - FAHASA</p>

                <br>
            </section>
        </div><!-- //container -->
    </footer>
    <!-- ========================= FOOTER END // ========================= -->



</body>
</html>