BookStore/BookStore/Controllers/CartController.cs
using BookStore.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStore.Models;
namespace BookStore.Controllers
{
    public class CartController : Controller
    {
        bookstoreEntities obj = new bookstoreEntities();
        // GET: Cart
        public ActionResult Index()
        {
            return View((List<CartModel>)Session["cart"]);
        }
        [HttpPost]
        public ActionResult AddToCart(string id, int quantity)
        {
            if (Session["cart"] == null)
            {
                List<CartModel> cart = new List<CartModel>();
                cart.Add(new CartModel { Sach = obj.Sach.Find(id), soLuong = quantity });
                Session["cart"] = cart;
                Session["count"] = 1;
            }
            else
            {
                List<CartModel> cart = (List<CartModel>)Session["cart"];
                //kiểm tra sản phẩm có tồn tại trong giỏ hàng chưa???
                int index = isExist(id);
                if (index != -1)
                {
                    //nếu sp tồn tại trong giỏ hàng thì cộng thêm số lượng
                    cart[index].soLuong += quantity;
                }
                else
                {
                    //nếu không tồn tại thì thêm sản phẩm vào giỏ hàng
                    cart.Add(new CartModel { Sach = obj.Sach.Find(id), soLuong = quantity });
                    //Tính lại số sản phẩm trong giỏ hàng
                    Session["count"] = Convert.ToInt32(Session["count"]) + 1;
                }
                Session["cart"] = cart;
            }
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }

        private int isExist(string id)
        {
            List<CartModel> cart = (List<CartModel>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].Sach.maSach.Equals(id))
                    return i;
            return -1;
        }

        //xóa sản phẩm khỏi giỏ hàng theo id
        public ActionResult Remove(string Id)
        {
            List<CartModel> li = (List<CartModel>)Session["cart"];
            li.RemoveAll(x => x.Sach.maSach == Id);
            Session["cart"] = li;
            Session["count"] = Convert.ToInt32(Session["count"]) - 1;
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }
    }
}

BookStore/BookStore/Controllers/PaymentController.cs
using BookStore.Context;
using BookStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.Controllers
{
    public class PaymentController : Controller
    {
        // GET: Payment
        public ActionResult Index()
        {
            bookstoreEntities obj= new bookstoreEntities();
            if (Session["idUser"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            else
            {
                // Lấy thông tin giỏ hàng từ biến session
                var lstCart = (List<CartModel>)Session["cart"];
                // Gán cho Order
                var objOrder = new Order();
                objOrder.UserId = int.Parse(Session["idUser"].ToString());
                objOrder.Name = "DonHang-" + DateTime.Now.ToString("yyyyMMddHHmmss");
                objOrder.CreatedOnUtc = DateTime.Now;
                objOrder.Status = 1;

                obj.Order.Add(objOrder);
                obj.SaveChanges();

                // Lấy thông tin và mỗi tác dụ vào bảng OrderDetail
                int idOrderDetail = objOrder.Id;
                List<OrderDetail> lstOrderDetail = new List<OrderDetail>();

                foreach (var item in lstCart)
                {
                    OrderDetail objj = new OrderDetail();
                    objj.Quantity = item.soLuong;
                    objj.OrderId = idOrderDetail;
                    objj.ProductID = item.Sach.maSach;

                    obj.OrderDetail.AddRange(lstOrderDetail);
                    obj.SaveChanges();
                }

                return View();
            }

        }
    }
}

BookStore/BookStore/Views/Cart/Index.cshtml
@model IEnumerable<BookStore.Models.CartModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


<script type="text/javascript">
    $(function () {
        $("#removecart").click(function () {
            var model = {};
            //lấy id sản phẩm
            model.Id = $("#productid").val();
            $.ajax({
                type: "POST",
                url: '@Url.Action("Remove", "Cart")',
                data:  JSON.stringify(model) ,
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function () {
                    $('#CartCount').text(@Session["count"] - 1);
                    $("#product-" + model.Id).remove();
                },
                error: function () {
                    alert("Lỗi trong khi thêm vào giỏ hàng!");
                }
            });
            return false;
        });
    });
</script>

<section class="section-content padding-y">
    <div class="container">
        <div class="row">
            <main class="col-md-9">
                <div class="card">

                    <table class="table table-borderless table-shopping-cart">
                        <thead class="text-muted">
                            <tr class="small text-uppercase">
                                <th scope="col">Sản Phẩm</th>
                                <th scope="col" width="120">Số Lượng</th>
                                <th scope="col" width="120">Giá</th>
                                <th scope="col" class="text-right" width="200"> </th>
                            </tr>
                        </thead>
                        <tbody>
                            @{int giaTong = 0; }
                            @if (Model != null)
                            {

                                foreach (var item in Model)
                                {

                                    <tr id="product-@item.Sach.maSach">
                                        <td>
                                            <figure class="itemside">
                                                <div class="aside"><img src="~/Content/images/items/@item.Sach.tenAnh" class="img-sm"></div>
                                                <figcaption class="info">
                                                    <a href="#" class="title text-dark">@item.Sach.tenSach</a>
                                                </figcaption>
                                            </figure>
                                        </td>
                                        <td>
                                            <span type="text">@item.soLuong</span>
                                        </td>
                                        <td>
                                            <div class="price-wrap">

                                                <var class="price">@item.Sach.giaSach</var>
                                            </div> <!-- price-wrap .// -->
                                        </td>
                                        <td class="text-right">
                                            <input type="hidden" value="@item.Sach.maSach" id="productid" />
                                            <a data-original-title="Save to Wishlist" title="" href="" class="btn btn-light" data-toggle="tooltip"> <i class="fa fa-heart"></i></a>

                                            <a href="" class="btn btn-light" id="removecart"> Xóa</a>
                                        </td>
                                    </tr>
                                    if(item.Sach.khuyenMai != null) { giaTong = (giaTong + (int)(item.Sach.giaSach * (100 - item.Sach.khuyenMai)) / 100)*item.soLuong; }
                                    else { giaTong =( giaTong + (int)item.Sach.giaSach)*item.soLuong; }

                                }
                            }
                            else
                            {
                                <p>Không có sản phẩm trong giỏ hàng</p>
                            }


                        </tbody>
                    </table>

                    <div class="card-body border-top">
                        <a href="@Url.Action("Index","Payment")" class="btn btn-primary float-md-right"> Thanh Toán <i class="fa fa-chevron-right"></i> </a>
                        <a href="@Url.Action("Index","Home")" class="btn btn-light"> <i class="fa fa-chevron-left"></i> Tiếp Tục Mua Hàng </a>
                    </div>
                </div> <!-- card.// -->

                <div class="alert alert-success mt-3">
                    <p class="icontext"><i class="icon text-success fa fa-truck"></i> Miễn Phí Vận Chuyển </p>
                </div>

            </main> <!-- col.// -->
            <aside class="col-md-3">
                <div class="card mb-3">
                    <div class="card-body">
                        <form>
                            <div class="form-group">
                                <label>Mã Giảm Giá</label>
                                <div class="input-group">
                                    <input type="text" class="form-control" name="" placeholder="Nhập Mã">
                                    <span class="input-group-append">
                                        <button class="btn btn-primary">Áp Dụng</button>
                                    </span>
                                </div>
                            </div>
                        </form>
                    </div> <!-- card-body.// -->
                </div>  <!-- card .// -->
                <div class="card">
                    <div class="card-body">
                       
                            <dl class="dlist-align">
                                <dt>Tổng Hóa Đơn:</dt>
                                <dd class="text-right">@(giaTong +",000 VND")</dd>
                            </dl>
                           
                            <hr>
                            <p class="text-center mb-3">
                                <img src="~/content/images/misc/payments.png" height="26">
                            </p>
                        
                    </div> <!-- card-body.// -->
                </div>  <!-- card .// -->
            </aside> <!-- col.// -->
        </div>

    </div> <!-- container .//  -->
</section>